name: Epic One
favicon: null
layout_spectrum: 0.8879659059457481
typography_spectrum: 0.9679900072515011
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.05099015706218779
  lightness: 0.42876006197184324
  saturation: 0.4975765838753432
  rhythmicContrast: 0.37452097120694816
purpose: []
